name: Windows Simple Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows
    timeout-minutes: 10
    defaults:
      run:
        shell: powershell
    steps:
      - run: Write-Host "Hello World"
